[project]
name = "wordcloud_app"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "wordcloud",
    "google-genai",
    "matplotlib",
    "streamlit",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"